#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

branch=$1

. ./cri-lock-repos

: ${BASE_TREE_LINUX:=git://xenbits.xen.org/people/ianc/linux-2.6.git}
: ${BASE_TAG_LINUX:=xen/next-2.6.32}
: ${BASE_LOCALREV_LINUX:=daily-cron.$branch.baseline}

case "$branch" in
#linux)
#	cd $repos/xen
#	git fetch -f $BASE_TREE_LINUX $BASE_TAG_LINUX:$BASE_LOCALREV_LINUX
#	git rev-parse $BASE_LOCALREV_LINUX^0
#	;;
*)
	exec ./ap-fetch-version-old "$@"
	;;
esac
