#!/bin/bash
set -e

branch=$1
. cri-lock-repos
. cri-common
select_xenbranch
. ap-common

: ${BASE_TAG_LINUX2639:=tested/2.6.39.x}
: ${BASE_LOCALREV_LINUX:=daily-cron.$branch.old}

: ${BASE_TREE_QEMU_UPSTREAM:=${TREE_QEMU_UPSTREAM/\/staging\//\/}}

if info_linux_tree "$branch"; then
	repo_tree_rev_fetch_git linux \
		$BASE_TREE_LINUX_THIS $BASE_TAG_LINUX_THIS $BASE_LOCALREV_LINUX
	exit 0
fi

case "$branch" in
xen*)
	./sg-hg-heads ssh $XENBITS '
	        set -e
	        cd HG/"'"$branch.hg"'"
	'
	;;
qemu-upstream-*)
        repo_tree_rev_fetch_git $branch \
		$BASE_TREE_QEMU_UPSTREAM master $LOCALREV_QEMU_UPSTREAM
        ;;
linux)
	repo_tree_rev_fetch_git linux \
		$BASE_TREE_LINUX $BASE_TAG_LINUX $BASE_LOCALREV_LINUX
	;;
linux-2.6.39)
	repo_tree_rev_fetch_git linux \
		$OLD_TREE_LINUX $OLD_TAG_LINUX2639 $OLD_LOCALREV_LINUX
	;;
linux-xen-*)
	repo_tree_rev_fetch_git linux \
		$OLD_TREE_LINUX $branch $OLD_LOCALREV_LINUX
	;;
osstest)
        cd $HOME/testing.git
        git-rev-parse incoming^0
        ;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
