#!/bin/bash
set -e

branch=$1
. cri-lock-repos
. cri-common
select_xenbranch
. ap-common

if info_linux_tree "$branch"; then
	echo $TREE_LINUX_THIS
	exit 0
fi

case "$branch" in
xen*)
        echo $TREE_XEN
	;;
qemu-upstream-*)
        echo $TREE_QEMU_UPSTREAM
        ;;
linux)
	echo $TREE_LINUX
	;;
linux-2.6.39)
	echo $TREE_LINUX2639
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
