#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -ex

branch=$1
revision=$2
. cri-lock-repos
. cri-common
select_xenbranch

: ${TAG_LINUX2639:=tested/2.6.39.x}

. ap-common

TREE_LINUX=$PUSH_TREE_LINUX
TREE_QEMU_MAINLINE=$PUSH_TREE_QEMU_MAINLINE
TREE_QEMU_UPSTREAM=$XENBITS:/home/xen/git/qemu-upstream-${xenbranch#xen-}.git
TREE_XEN=$PUSH_TREE_XEN
TREE_LIBVIRT=$PUSH_TREE_LIBVIRT
TREE_RUMPUSERXEN=$PUSH_TREE_RUMPUSERXEN

if info_linux_tree "$branch"; then
	cd $repos/linux
	git push $GITFORCEFLAG_TREE_LINUX_THIS \
		$PUSH_TREE_LINUX_THIS $revision:$PUSH_TAG_LINUX_THIS
        exit 0
fi

case "$branch" in
xen-3.*)
	cd $repos/$branch.hg
	hg push -r "$revision" ssh://$XENBITS//home/xen/HG/$branch.hg
	;;
xen-unstable)
	cd $repos/xen
	git push $TREE_XEN $revision:master
	;;
xen-*-testing)
	cd $repos/xen
	xenversion=$branch
	xenversion=${branch%-testing}
	xenversion=${xenversion#xen-}
	git push $TREE_XEN $revision:stable-$xenversion
	;;
qemu-mainline)
	cd $repos/qemu-mainline
	git push $TREE_QEMU_MAINLINE $revision:refs/heads/mainline/xen-tested-master
	;;
qemu-upstream-*)
	cd $repos/$branch
        git push $TREE_QEMU_UPSTREAM $revision:master
        ;;
linux-3.*)
	cd $repos/linux
	git push $TREE_LINUX $revision:tested/$branch
	;;
linux-2.6.39)
	cd $repos/linux
	git push $TREE_LINUX $revision:$TAG_LINUX2639
	;;
linux-xen-*)
        cd $repos/linux
        git push $TREE_LINUX $revision:refs/heads/$branch
        ;;
libvirt)
	cd $repos/libvirt
	git push $TREE_LIBVIRT $revision:xen-tested-master
	;;
rumpuserxen)
	cd $repos/rumpuserxen
	git push $TREE_RUMPUSERXEN $revision:xen-tested-master
	;;
gnulib-libvirt)
	# No gate
	echo "gnulib-libvirt has not push gate, refusing to push" >&2
	exit 1
	;;
osstest)
	git push $HOME/testing.git $revision:incoming
	git push $XENBITS:/home/xen/git/osstest.git $revision:master
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
