#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

branch=$1
. cri-lock-repos
. cri-common
select_xenbranch
. ap-common

if info_linux_tree "$branch"; then
	echo $TREE_LINUX_THIS
	exit 0
fi

case "$branch" in
xen*)
        echo $TREE_XEN
	;;
qemu-mainline)
        echo $TREE_QEMU_MAINLINE
        ;;
qemu-upstream-*)
        echo $TREE_QEMU_UPSTREAM
        ;;
linux)
	echo $TREE_LINUX
	;;
linux-2.6.39)
	echo $TREE_LINUX2639
	;;
linuxfirmware)
	echo $UPSTREAM_TREE_LINUXFIRMWARE
	;;
libvirt)
	echo $TREE_LIBVIRT
	;;
gnulib-libvirt)
	echo $TREE_GNULIB_LIBVIRT
	;;
rumpuserxen)
	echo $TREE_RUMPUSERXEN
	;;
osstest)
	echo none:;
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
