#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -ex -o posix

branch=$1
revision=$2
. ./cri-lock-repos
. ./cri-common
select_xenbranch

if [ "x$revision" = x ]; then
	echo >&2 "NOT pushing empty revision!"; exit 1
fi

: ${TAG_LINUX2639:=tested/2.6.39.x}

. ./ap-common

TREE_LINUX=$PUSH_TREE_LINUX
TREE_QEMU_UPSTREAM=$PUSH_TREE_QEMU_UPSTREAM
TREE_XEN=$PUSH_TREE_XEN
TREE_LIBVIRT=$PUSH_TREE_LIBVIRT
TREE_RUMPUSERXEN=$PUSH_TREE_RUMPUSERXEN
TREE_SEABIOS=$PUSH_TREE_SEABIOS
TREE_OVMF=$PUSH_TREE_OVMF

if info_linux_tree "$branch"; then
	cd $repos/linux
	git push $GITFORCEFLAG_TREE_LINUX_THIS \
		$PUSH_TREE_LINUX_THIS $revision:$PUSH_TAG_LINUX_THIS
        exit 0
fi

case "$branch" in
xen-3.*)
	cd $repos/$branch.hg
	hg push -r "$revision" ssh://$XENBITS//home/xen/HG/$branch.hg
	;;
xen-unstable)
	cd $repos/xen
	git push $TREE_XEN $revision:refs/heads/master
	;;
xen-unstable-smoke)
	cd $repos/xen
	git push $TREE_XEN $revision:refs/heads/smoke
	;;
xen-*-testing)
	cd $repos/xen
	xenversion=$branch
	xenversion=${branch%-testing}
	xenversion=${xenversion#xen-}
	git push $TREE_XEN $revision:refs/heads/stable-$xenversion
	;;
qemu-mainline)
	cd $repos/qemu-mainline
	git push $TREE_QEMU_UPSTREAM $revision:refs/heads/upstream-tested
	;;
qemu-upstream-unstable)
	cd $repos/$branch
        git push $TREE_QEMU_UPSTREAM $revision:refs/heads/master
        ;;
qemu-upstream-*-testing)
	branchcore=${branch#qemu-upstream-}
	branchcore=${branchcore%-testing}
	cd $repos/$branch
	git push $TREE_QEMU_UPSTREAM $revision:refs/heads/stable-$branchcore

	# For now also push to the old split trees for historical
	# branches only (qemu-upstream started with xen-4.2-testing
	# and the split trees end at xen-4.6-testing)
	case "$branchcore" in
	    4.[23456])
		tree=$XENBITS:/home/xen/git/qemu-upstream-${branchcore}-testing.git
		git push $tree $revision:refs/heads/master
		;;
	esac
        ;;
linux-3.*)
	cd $repos/linux
	git push $TREE_LINUX $revision:refs/heads/tested/$branch
	;;
linux-2.6.39)
	cd $repos/linux
	git push $TREE_LINUX $revision:$TAG_LINUX2639
	;;
linux-xen-*)
        cd $repos/linux
        git push $TREE_LINUX $revision:refs/heads/$branch
        ;;
libvirt)
	cd $repos/libvirt
	git push $TREE_LIBVIRT $revision:refs/heads/xen-tested-master
	;;
rumpuserxen)
	cd $repos/rumpuserxen
	git push $TREE_RUMPUSERXEN $revision:refs/heads/xen-tested-master
	;;
seabios)
	cd $repos/seabios
	git push $TREE_SEABIOS $revision:refs/heads/xen-tested-master
	;;
ovmf)
	cd $repos/ovmf
	git push $TREE_OVMF $revision:refs/heads/xen-tested-master
	;;
osstest)
	git push $HOME/testing.git $revision:production
	if [ x"$TREEBRANCH_OSSTEST_UPSTREAM" != x ] ; then
	    # could push to instance specific location, but
	    # certainly not to master instance's xenbits repo!
	    :
	else
	    git push $XENBITS:/home/xen/git/osstest.git $revision:master
	fi
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
