#!/bin/bash
set -ex

branch=$1
revision=$2
. cri-lock-repos
. cri-common
select_xenbranch

: ${TAG_LINUX:=master}
: ${TAG_LINUX2639:=tested/2.6.39.x}
: ${TREE_QEMU_UPSTREAM:=$XENBITS:git/qemu-upstream-${xenbranch#xen-}.git}

. ap-common

TREE_LINUX=$PUSH_TREE_LINUX

if info_linux_tree "$branch"; then
	cd $repos/linux
	git push $GITFORCEFLAG_TREE_LINUX_THIS \
		$PUSH_TREE_LINUX_THIS $revision:$PUSH_TAG_LINUX_THIS
        exit 0
fi

case "$branch" in
xen*)
	cd $repos/$branch.hg
	hg push -r "$revision" ssh://$XENBITS/HG/$branch.hg
	;;
qemu-upstream-*)
	cd $repos/$branch
        git push $TREE_QEMU_UPSTREAM $revision:master
        ;;
linux)
	cd $repos/linux
	git push $TREE_LINUX $revision:$TAG_LINUX
	;;
linux-2.6.39)
	cd $repos/linux
	git push $TREE_LINUX $revision:$TAG_LINUX2639
	;;
linux-xen-*)
        cd $repos/linux
        git push $TREE_LINUX $revision:refs/heads/$branch
        ;;
osstest)
	git push $HOME/testing.git $revision:incoming
	git push $XENBITS:git/osstest.git $revision:master
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
