#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -ex

. cri-args-hostlists
. ap-common
branch=$1; shift
select_branch
info_linux_tree $branch ||:

tree_bisect=tree-bisect

check_stop daily.

determine_tree () {
	local treevarwhich=$1
	local tsrcvarlhs=$2
	local tsrcvarrhs=$3
	if [ "x$treevarwhich" = x ]; then return; fi

	for tsrcvarwhich in TREE TREEVCS; do
		eval "ttreeval=\$${tsrcvarlhs}${tsrcvarwhich}${tsrcvarrhs}"
		if [ "x$ttreeval" = x ]; then return; fi
		eval "${tsrcvarwhich}_${treevarwhich}=\$ttreeval"
		export "${tsrcvarwhich}_${treevarwhich}"
	done
}

determine_version () {
	local tversionvar=$1
	local tbranch=$2
	local treevarwhich=$3
	if [ "x$tbranch" = "x$branch" ] && ! $force_baseline; then
                if [ "x$FORCE_REVISION" != x ]; then
                        tversion="$FORCE_REVISION"
                else
        		tversion=`./ap-fetch-version "$tbranch"`
                fi
		determine_tree "$treevarwhich" "" _${treevarwhich}
		determine_tree "$treevarwhich" "" _${treevarwhich}_THIS
	else
		tversion=`./ap-fetch-version-baseline "$tbranch"`
		determine_tree "$treevarwhich" BASE_ _${treevarwhich}
		determine_tree "$treevarwhich" BASE_ _${treevarwhich}_THIS
	fi
	eval "$tversionvar=$tversion"
}

fetch_version () {
	determine_version fetch_version_result "$@"
	printf '%s\n' "$fetch_version_result"
}

treeurl=`./ap-print-url $branch`

force_baseline=false
skipidentical=true
wantpush=$OSSTEST_PUSH

if [ "x$OLD_REVISION" = x ]; then
        OLD_REVISION="`./ap-fetch-version-old $branch`"
        export OLD_REVISION
fi

check_tested () {
	./sg-check-tested --debug --branch=$branch \
	  --blessings=${DAILY_BRANCH_TESTED_BLESSING:-$OSSTEST_BLESSING} \
	  "$@"
}

testedflight=`check_tested --revision-$tree="$OLD_REVISION"`

if [ "x$testedflight" = x ]; then
        wantpush=false
        skipidentical=false
        force_baseline=true
	if [ "x$treeurl" != xnone: ]; then
		treearg=--tree-$tree=$treeurl
	fi
	tested_revision=`check_tested $treearg --print-revision=$tree`
	if [ "x$tested_revision" != x ]; then
		OLD_REVISION="$tested_revision"
	fi
fi

if [ "x$REVISION_XEN" = x ]; then
        REVISION_XEN="`fetch_version $xenbranch`"
        export REVISION_XEN
fi
if [ "x$REVISION_QEMU_UPSTREAM" = x ]; then
	case "$xenbranch" in
        xen-3.*|xen-4.[01]-*)
        	;;
	*)
		REVISION_QEMU_UPSTREAM="`fetch_version \
				qemu-upstream-${xenbranch#xen-}`"
		;;
        esac
        export REVISION_QEMU_UPSTREAM
fi
if [ "x$REVISION_LINUX" = x ]; then
	determine_version REVISION_LINUX ${linuxbranch:-linux} LINUX
        export REVISION_LINUX
fi
if [ "x$REVISION_LINUX_ARM" = x ]; then
	determine_version REVISION_LINUX_ARM ${linuxbranch:-linux-arm-xen} \
		LINUX_ARM
        export REVISION_LINUX_ARM
fi
if [ "x$REVISION_LINUXFIRMWARE" = x ]; then
	determine_version REVISION_LINUXFIRMWARE linuxfirmware
        export REVISION_LINUXFIRMWARE
fi

case "$tree" in
xen)
        realtree=$xenbranch
	NEW_REVISION=$REVISION_XEN
	;;
linux)
        realtree=linux
	NEW_REVISION=$REVISION_LINUX
	export REVISION_LINUX_OLD=disable
	: ${GITFORCEFLAG:=$GITFORCEFLAG_TREE_LINUX_THIS}
	;;
osstest)
	determine_version REVISION_OSSTEST osstest
        realtree=
	NEW_REVISION=$REVISION_OSSTEST
	git reset --hard $REVISION_OSSTEST
	;;
qemuu)
	realtree=qemu-upstream-${xenbranch#xen-}
	NEW_REVISION=$REVISION_QEMU_UPSTREAM
        ;;
linuxfirmware)
	realtree=linuxfirmware
	NEW_REVISION=$REVISION_LINUXFIRMWARE
        ;;
*)
	NEW_REVISION=''
	wantpush=false
	;;
esac

if [ "x$NEW_REVISION" = "x$OLD_REVISION" ]; then
        wantpush=false
	for checkbranch in x $BRANCHES_ALWAYS; do
		if [ x"$branch" = x"$checkbranch" ]; then
			skipidentical=false
		fi
	done
	if $skipidentical; then
		echo 'up to date'
                exit 0
        fi
fi

$DAILY_BRANCH_PREMAKE_HOOK
flight=`./make-flight $branch $xenbranch $OSSTEST_BLESSING "$@"`
$DAILY_BRANCH_POSTMAKE_HOOK

heading=tmp/$flight.heading-info
: >$heading
sgr_args+=" --include-begin=$heading"

if $force_baseline; then
	subject_prefix="[$branch baseline test] "
	cat >>$heading <<END
"Old" tested version had not actually been tested; therefore in this
flight we test it, rather than a new candidate.  The baseline, if
any, is the most recent actually tested revision.

END
fi

revlog=tmp/$flight.revision-log

case "$NEW_REVISION/$OLD_REVISION" in
*/*[^0-9a-f]* | *[^0-9a-f]*/*)
        echo >&2 "NO SGR COMPARISON badchar $NEW_REVISION/$OLD_REVISION"
        ;;
[0-9a-f]*/)
        sgr_args+=" --this-$tree=$NEW_REVISION"
	;;
[0-9a-f]*/[0-9a-f]*)
        sgr_args+=" --machine-readable-output=$mrof"
        sgr_args+=" --this-$tree=$NEW_REVISION"
        sgr_args+=" --that-$tree=$OLD_REVISION"

        if [ "$realtree" ] && [ "x$NEW_REVISION" != "x$OLD_REVISION" ] \
	   && [ "x$GITFORCEFLAG" = x ]; then
                ./adhoc-revtuple-generator >$revlog -S \
                        "$treeurl#$OLD_REVISION-$NEW_REVISION" \

                case "$realtree" in
                xen-4*|xen-unstable)
                    oldqemu=`./ap-qemu-revision $realtree $OLD_REVISION`
                    newqemu=`./ap-qemu-revision $realtree $NEW_REVISION`
                    if [ "$oldqemu" ] && [ "$newqemu" ]; then
                        echo >>$revlog ========================================
                        ./adhoc-revtuple-generator >>$revlog -S \
                            "`./ap-qemu-url $realtree`#$oldqemu-$newqemu"
                    else
                        echo >>$revlog '(qemu changes not included)'
                    fi
                    ;;
                esac

                cat <<END >tmp/$flight.people-touched
People who touched revisions under test:
END
                ./adhoc-people-touched-filter <$revlog \
                        >>tmp/$flight.people-touched
                sgr_args+=" --include=tmp/$flight.people-touched"
        fi
        ;;
*)
        echo >&2 "NO SGR COMPARISON wronglen $NEW_REVISION/$OLD_REVISION"
        ;;
esac

: $flight $branch $OSSTEST_BLESSING $sgr_args
$DAILY_BRANCH_PREEXEC_HOOK
execute_flight $flight $OSSTEST_BLESSING
start_email $flight $branch "$sgr_args" "$subject_prefix"

push=false
if grep '^tolerable$' $mrof >/dev/null 2>&1; then push=$wantpush; fi
if test -f $branch.force; then push=$OSSTEST_PUSH; fi
if grep -xF $NEW_REVISION $branch.force-rev; then push=$OSSTEST_PUSH; fi
if test -f $branch.block; then push=false; fi

if test -e $mrof && test -e $tree_bisect; then
	with-lock-ex -w $tree_bisect/$mrof.lock bash -xec "
		rm -f $tree_bisect/$mrof.in.new
		cp $mrof $tree_bisect/$mrof.in.new
		cd $tree_bisect
		mv -f $mrof.in.new $mrof.in
	"
fi

if ! $wantpush; then
        echo
        echo "Published tested tree is already up to date."
        echo
elif $push; then
        echo
        echo "Pushing revision $to_push:"
        echo
        to_push=`sed -n "s/^version this $tree //p" <$mrof`
	case "$to_push" in
	*[^0-9a-f]*)
		echo >&2 "BAD PUSH REVISION $to_push"
		;;
	[0-9a-f]*)
	        if ./ap-push $branch $to_push 2>&1; then
			rm -f $branch.push $branch.force-rev
			perl -i~ -pe '
	                        next unless m/^Subject: / && !$subsequent++;
	                        s/$/ - PUSHED/;
	                ' tmp/$flight.email
	        fi
		;;
	*)	echo >&2 "BAD/MISSING PUSH REVISION $to_push" ;;
	esac
else
        echo
        echo Not pushing.
        echo
fi

if [ -f $revlog ]; then
    revlog_lines=`wc -l <$revlog`
    if [ $revlog_lines -lt 300 ]; then
        echo ------------------------------------------------------------
        cat $revlog
    else
        echo "(No revision log; it would be" $revlog_lines "lines long.)"
    fi
fi

publish_send_email $flight
