#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -ex

. cri-args-hostlists

branch=$1; shift
tree=linux
xenbranch=xen-unstable

case "$branch" in
linux-next)
	url=git://git.kernel.org/pub/scm/linux/kernel/git/sfr/linux-next.git
	;;
*)
	echo >&2 "unknown cr-external-linux branch"
	exit 1
	;;
esac

select_branch

check_stop external-linux.

export REVISION_LINUX_OLD=disable
export REVISION_XEN="`./ap-fetch-version-baseline $xenbranch`"
export TREE_LINUX="$url"

flight=`./make-flight $branch $xenbranch $OSSTEST_BLESSING "$@"`

execute_flight $flight $OSSTEST_BLESSING
start_email $flight "$branch"
publish_send_email $flight
