#!/usr/bin/perl -w

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


use strict qw(refs vars);
use Fcntl qw(:flock);
use Osstest;

our %c;

readglobalconfig();

my $push_harness = 0;
if (@ARGV && $ARGV[0] eq '--push-harness') {
    shift @ARGV;
    $push_harness = 1;
}

die "usage: ./cr-publish-flight-logs <flight>" unless @ARGV==1;

my $flight= shift @ARGV;
die unless $flight =~ m/^\d+$/;

open LOCK, "> $c{GlobalLockDir}/publish-lock" or die $!;
flock LOCK, LOCK_EX or die $!;

if ($push_harness) {
    my $githost= $c{HarnessPublishGitUserHost};
    my $gitdir= $c{HarnessPublishGitRepoDir};

    exit 0 if (!$githost || !$gitdir);

    system_checked("git push $githost:$gitdir HEAD:refs/heads/flight-$flight");
    system_checked("ssh $githost 'cd $gitdir && git update-server-info'");
}

sub copydir ($$) {
    my ($src,$dst) = @_;
    my @cmd= qw(rsync --compress --compress-level=9 --stats --delete -auH);
    push @cmd, '-e', 'ssh -o batchmode=yes';
    #--bwlimit=50
    push @cmd, $src, $dst;
    print "+ @cmd\n";
    $!=0; $?=0; system @cmd; die "rsync $? $!" if $? or $!;
}

copydir("$c{Logs}/$flight/", "$c{LogsPublish}/$flight");
copydir("$c{Results}/", "$c{ResultsPublish}");
