#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

csreadconfig();

@ARGV==2 or die $!;
our ($intended,$branch) = @ARGV;

my ($flight) =
    db_retry($dbh_tests,[qw(flights)], sub {
	my $fl = $mjobdb->flight_create($intended,$branch);
	$mjobdb->dbfl_check($fl,'constructing');
	return $fl;
    });

printf "%s\n", $flight;
