#!/usr/bin/perl -w
#
# args:
#   <flight> <blessing> <oldblessings>

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


use strict qw(vars);
use DBI;
use Osstest;

csreadconfig();

die unless @ARGV >= 3;
my ($flight,$blessing,@oldblessings) = @ARGV;

my $q= $dbh_tests->
    prepare("UPDATE FLIGHTS SET blessing=? WHERE flight=?");

db_retry($dbh_tests,[qw(flights)], sub {
    dbfl_check($flight, [@oldblessings]);
    $q->execute($blessing, $flight);
    $q->finish();
});
