#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

branch=$1
xenbranch=$2
blessing=$3
buildflight=$4

flight=`./cs-flight-create $blessing $branch`

. ap-common
. cri-common
. mfi-common

defsuite=`getconfig DebianSuite`
defguestsuite=`getconfig GuestDebianSuite`

if [ x$buildflight = x ]; then

  if [ "x$BUILD_LVEXTEND_MAX" != x ]; then
     BUILD_RUNVARS+=" build_lvextend_max=$BUILD_LVEXTEND_MAX "
  fi

  create_build_jobs

else

  bfi=$buildflight.

fi

job_create_test_filter_callback () {
  local job=$1; shift
  local recipe=$1; shift
  local toolstack=$1; shift
  local xenarch=$1; shift
  local dom0arch=$1; shift

  case "$branch" in
    qemu-upstream-*)
      case " $* " in
        *" device_model_version=qemu-xen "*)
          ;;
        *)
          : "suppressed $job"
          return 1;;
      esac
      ;;
    libvirt)
      if [ x$toolstack != xlibvirt ] ; then return 1; fi
      ;;
    *)
      case "$job" in
        *-qemuu-*)
          if [ "x$toolstack" != xxl ]; then return 1; fi
          ;;
      esac
      ;;
  esac

  return 0;
}

test_matrix_branch_filter_callback () {
  case "$xenarch" in
  armhf)
        case "$branch" in
        linux-3.0) return 1;;
        linux-3.4) return 1;;
        linux-mingo-tip-master) return 1;;
        linux-*) ;;
        qemu-*) return 1;;
        esac
        ;;
  i386|amd64)
        case "$branch" in
        linux-arm-xen) return 1;;
        esac
        ;;
  esac

  return 0
}

do_freebsd_tests () {

  if [ $xenarch != amd64 -o $dom0arch != i386 -o "$kern" != "" ]; then
    return
  fi

  for freebsdarch in amd64 i386; do

 job_create_test test-$xenarch$kern-$dom0arch$qemuu_suffix-freebsd10-$freebsdarch \
                        test-freebsd xl $xenarch $dom0arch \
                        freebsd_arch=$freebsdarch \
 freebsd_image=${FREEBSD_IMAGE_PREFIX-FreeBSD-10.0-RELEASE-}$freebsdarch${FREEBSD_IMAGE_SUFFIX--20140116-r260789.qcow2.xz} \
                        all_hostflags=$most_hostflags

  done
}

do_hvm_winxp_tests () {
  for vcpus in '' 1; do
    case "$vcpus" in
      '') vcpus_runvars=''; vcpus_suffix='' ;;
      *) vcpus_runvars=guests_vcpus=$vcpus; vcpus_suffix=-vcpus$vcpus ;;
    esac

    if [ "x$vcpus" != x ] && \
       [ "$xenarch$kern-$dom0arch" != "amd64-i386" ]; then
      continue
    fi

    if [ x$test_xend != xy ] ; then
      toolstack="xl"
    else
      toolstack=
    fi

    if [ x$toolstack = x ] ; then
      stripy toolstack xend xl \
            "$vcpus" 1 \
            "$kern" '' \
            "$xenarch" i386 \
            "$dom0arch" i386
    fi

    toolstack_runvars="toolstack=$toolstack"

    job_create_test \
            test-$xenarch$kern-$dom0arch-$toolstack$qemuu_suffix-winxpsp3$vcpus_suffix \
            test-win $toolstack $xenarch $dom0arch $qemuu_runvar \
            win_image=winxpsp3.iso $vcpus_runvars   \
            all_hostflags=$most_hostflags,hvm

  done
}

do_hvm_win7_x64_tests () {
  if [ $xenarch != amd64 ]; then
    return
  fi

  job_create_test test-$xenarch$kern-$dom0arch-xl$qemuu_suffix-win7-amd64 \
            test-win xl $xenarch $dom0arch $qemuu_runvar \
            win_image=win7-x64.iso \
            all_hostflags=$most_hostflags,hvm
}

do_hvm_debian_ovmf_tests() {
  if [ $xenarch != amd64 -o "x$qemuu_suffix" != "x-qemuu" ]; then
    return
  fi

  job_create_test test-$xenarch$kern-$dom0arch-xl$qemuu_suffix-ovmf-amd64 \
    test-debianhvm xl $xenarch $dom0arch $qemuu_runvar \
    ovmf_image=debian-7.2.0-amd64-CD-1.iso \
    all_hostflags=$most_hostflags,hvm
}

do_hvm_rhel6_tests () {
  if [ $xenarch != amd64 -o $dom0arch != i386 -o "$kern" != "" ]; then
    return
  fi

  for cpuvendor in amd intel; do

    job_create_test test-$xenarch$kern-$dom0arch$qemuu_suffix-rhel6hvm-$cpuvendor \
                                            test-rhelhvm xl $xenarch $dom0arch \
            redhat_image=rhel-server-6.1-i386-dvd.iso \
            all_hostflags=$most_hostflags,hvm-$cpuvendor \
            $qemuu_runvar

  done
}

do_sedf_tests () {
  if [ $xenarch != amd64 -o $dom0arch != amd64 ]; then
    return
  fi

  for pin in '' -pin; do
    job_create_test test-$xenarch$kern-$dom0arch-xl-sedf$pin  \
       test-debian xl $xenarch $dom0arch                      \
            guests_vcpus=4                                    \
            xen_boot_append="sched=sedf loglvl=all ${pin:+dom0_vcpus_pin}" \
            linux_boot_append='loglevel=9 debug'              \
            $debian_runvars all_hostflags=$most_hostflags
  done
}

do_credit2_tests () {
  if [ $xenarch != amd64 -o $dom0arch != i386 ]; then
    return
  fi

  job_create_test test-$xenarch$kern-$dom0arch-xl-credit2             \
       test-debian xl $xenarch $dom0arch                              \
            guests_vcpus=4 xen_boot_append='sched=credit2'            \
            $debian_runvars all_hostflags=$most_hostflags
}

do_passthrough_tests () {
  if [ $xenarch != amd64 -o $dom0arch != amd64 -o "$kern" != "" ]; then
    return
  fi

  for cpuvendor in intel; do
    job_create_test test-$xenarch$kern-$dom0arch-xl-pcipt-intel       \
                    test-debian-nomigr xl $xenarch $dom0arch          \
            guests_vcpus=4                                            \
            $debian_runvars debian_pcipassthrough_nic=host            \
            all_hostflags=$most_hostflags,hvm-$cpuvendor,pcipassthrough-nic

  done
}

do_pygrub_tests () {
  if [ $xenarch != amd64 -o $dom0arch != amd64 -o "$kern" != "" ]; then
    return
  fi

  job_create_test test-$xenarch$kern-$dom0arch-pygrub   \
    test-debian-di xl $xenarch $dom0arch                \
      debian_arch=amd64                                 \
      debian_dist=$guestsuite                           \
      debian_method=netboot                             \
      debian_bootloader=pygrub                          \
      all_hostflags=$most_hostflags
}

do_pvgrub_tests () {
  if [ $xenarch != amd64 -o $dom0arch != amd64 -o "$kern" != "" ]; then
    return
  fi

  job_create_test test-$xenarch$kern-$dom0arch-amd64-pvgrub     \
    test-debian-di xl $xenarch $dom0arch                        \
      debian_arch=amd64                                         \
      debian_dist=$guestsuite                                   \
      debian_method=netboot                                     \
      debian_bootloader=pvgrub                                  \
      all_hostflags=$most_hostflags                             \

  job_create_test test-$xenarch$kern-$dom0arch-i386-pvgrub      \
    test-debian-di xl $xenarch $dom0arch                        \
      debian_arch=i386                                          \
      debian_dist=$guestsuite                                   \
      debian_method=netboot                                     \
      debian_bootloader=pvgrub                                  \
      all_hostflags=$most_hostflags
}

test_matrix_do_one () {

  # Basic PV Linux test with xl

  job_create_test test-$xenarch$kern-$dom0arch-xl test-debian xl \
            $xenarch $dom0arch                                   \
            $debian_runvars all_hostflags=$most_hostflags

  job_create_test test-$xenarch$kern-$dom0arch-libvirt test-debian libvirt \
            $xenarch $dom0arch                                       \
            $debian_runvars all_hostflags=$most_hostflags

  # No further arm tests at the moment
  if [ $dom0arch = armhf ]; then
      return
  fi

  # xend tests for versions <= 4.4 only
  case "$xenbranch" in
  xen-3.*-testing) test_xend=y ;;
  xen-4.0-testing) test_xend=y ;;
  xen-4.1-testing) test_xend=y ;;
  xen-4.2-testing) test_xend=y ;;
  xen-4.3-testing) test_xend=y ;;
  xen-4.4-testing) test_xend=y ;;
  *)               test_xend=n ;;
  esac

  # xend PV guest test on x86 only
  if [ x$test_xend = xy -a \( $dom0arch = "i386" -o $dom0arch = "amd64" \) ]; then
    job_create_test test-$xenarch$kern-$dom0arch-pv test-debian xend \
            $xenarch $dom0arch                                       \
            $debian_runvars all_hostflags=$most_hostflags
  fi

  do_freebsd_tests

  for qemuu_suffix in '' -qemut -qemuu; do
    case "$qemuu_suffix" in
    '')
          qemuu_runvar=''
          ;;
    -qemut)
          qemuu_runvar=device_model_version=qemu-xen-traditional
          ;;
    -qemuu)
          case $xenbranch in
          xen-3.*-testing) continue;;
          xen-4.0-testing) continue;;
          xen-4.1-testing) continue;;
          esac
          qemuu_runvar=device_model_version=qemu-xen
          ;;
    esac

    do_hvm_winxp_tests
    do_hvm_win7_x64_tests
    do_hvm_rhel6_tests

    do_hvm_debian_ovmf_tests

  done # qemuu_suffix

  # Test live migration
  job_create_test test-$xenarch$kern-$dom0arch-pair test-pair \
            $onetoolstack $xenarch $dom0arch \
            !host !host_hostflags \
            $debian_runvars \
            all_hostflags=$most_hostflags,equiv-1

  do_sedf_tests
  do_credit2_tests

  if [ $xenarch = amd64 -a $dom0arch = i386 ]; then

  job_create_test test-$xenarch$kern-$dom0arch-xl-multivcpu \
                    test-debian xl $xenarch $dom0arch guests_vcpus=4  \
                    $debian_runvars all_hostflags=$most_hostflags

  fi

  do_passthrough_tests

  do_pygrub_tests
  do_pvgrub_tests
}

test_matrix_iterate

echo $flight

# Local variables:
# mode: sh
# sh-basic-offset: 2
# indent-tabs-mode: nil
# End:
