#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

. cri-common

if [ $# != 0 ]; then echo >&2 'usage: mg-clear-git-caches'; exit 1; fi

cache=`getconfig GitCacheLocal`

for lockfile in $cache/*/lock; do
	hostdir=${lockfile%/lock}
	host=${hostdir##*/}
	printf "===== %s =====\n" $host
	aside=$cache/$host.$$.`date +%s`.to-delete
	mkdir $aside
	if ! ./mg-allocate -U 10 $host; then continue; fi
	set +e
	mv $hostdir $aside/.
	r=$?
	set -e
	./mg-allocate !$host
	if [ $r != 0 ]; then echo >&2 ' failed'; exit $r; fi
	printf ' deleting\n'
	sudo rm -rf $aside
done
