#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


usage () { cat <<END

./mg-execute-flight [options] <flight>
 options:
    -B<blessing>
    -E<email>
    -f<basisflight>

END
}

set -e

badusage () { echo >&2 "bad usage"; usage >&2; exit 126; }

while [ $# != 0 ]; do
	arg=$1; shift
        case "$arg" in
        -B?*)	blessing=${arg#-B}			;;
        -E?*)	email=${arg#-E}				;;
	-f?*)	basisflightopt=--that-flight=${arg#-f}	;;
	[0-9]*)	if [ "x$flight" != x ]; then badusage; fi
		flight=$arg				;;
	*)	badusage				;;
	esac
done

if [ x"$flight" = x ]; then badusage; fi

: ${blessing:=play}
: ${email:=`whoami`}

set +e
tty=`exec 2>/dev/null; tty`
branch=`exec 2>/dev/null; git-branch | sed -n 's/^\* //p'`
set -e

export OSSTEST_RESOURCE_PRIORITY=${OSSTEST_RESOURCE_PRIORITY--8}
export OSSTEST_RESOURCE_PREINFO="[adhoc $blessing]\
 <${PWD##*/}${branch:+ }$branch${tty:+ }$tty>"

 : ${OSSTEST_HTMLPUB_DIR:=`getconfig Logs`}

(./sg-execute-flight $flight $blessing ||
 echo "sg-execute-flight $flight $blessing failed: $?") \
 >tmp/$flight.transcript 2>&1

./sg-report-flight $basisflightopt \
	--html-dir=$OSSTEST_HTMLPUB_DIR/$flight/ \
	$flight >tmp/$flight.report

subject=`sed -n 1p <tmp/$flight.report`

exec >tmp/$flight.email 
cat <<END
To: $email
Subject: [adhoc test] $subject

$OSSTEST_RESOURCE_PREINFO
END

git-log -n1 --pretty=format:'harness %h: %s' | perl -pe 's/(.{70}).+/$1.../'
echo

cat <tmp/$flight.report

echo ============================================================
cat <tmp/$flight.transcript

exec >&2

/usr/sbin/sendmail -odi -oee -oi -t <tmp/$flight.email
mv tmp/$flight.email tmp/$flight.email.sent
