#!/usr/bin/perl -w
# prints on stdout a list of all the "branches"
# mentioned in cr-daily-branch or crontab

use strict;
use Sort::Versions;

our %branches;

foreach my $f (qw(cr-for-branches crontab)) {
    open C, $f or die $!;
    while (<C>) {
        next unless m/(?:EXTRA_)?BRANCHES[:+]?='?([-.0-9a-z ]+)/;
        $branches{$_}=1 foreach split /\s+/, $1;
    }
    close C or die $!;
}

delete $branches{maintjobs};

print $_,"\n" or die $! foreach sort { versioncmp($a, $b) } keys %branches;
