#!/usr/bin/perl -w

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


use strict qw(vars refs);
use JSON;
use Data::Dumper;
use DBI;
use Osstest;

csreadconfig();

my $walker = 'plan';

if (@ARGV && $ARGV[0] =~ m/^-w(.+)$/) {
    $walker = $1;
    shift @ARGV;
}

my $f= sprintf "data-$walker-debug-%s.txt", time;

printf "%s\n", $f;

open STDOUT, ">$f" or die $!;

print "==========ARGS==========\n";
foreach my $arg (@ARGV) {
    print "==========\n", $arg, "\n----------\n";
    my $jobj= eval { from_json($arg) };
    if ($jobj) {
	print Dumper($jobj);
    } else {
	print $@,"\n";
    }
}

print "==========data-$walker.pl==========\n";

system 'cat data-$walker.pl 2>&1';

print "==========resources==========\n";

system "psql -d osstestdb -c \"select * from resource_sharing s full outer join resources r on r.restype = 'share-' || s.restype and r.resname = s.resname full outer join tasks t on r.owntaskid=t.taskid order by live, r.resname, shareix, r.restype, taskid\" 2>&1";

print "==========\n";
