#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2014 Citrix Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

usage(){
	cat <<END
usage: ./sa-forget-flight <database> <flight>
END
}

if [ $# -ne 2 ] ; then
	usage >&2
	exit 1
fi

db="$1"
flight="$2"

sqlite3 "$db" <<END
	DELETE FROM runvars WHERE flight='$flight';
	DELETE FROM jobs    WHERE flight='$flight';
	DELETE FROM flights WHERE flight='$flight';
END
