#!/bin/bash

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# usage:  sg-hg-heads COMMAND ARGS...
#  where COMMAND ARGS SCRIPT
#  runs shell script SCRIPT in an appropriate directory and place

set -e -o posix

result=`"$@" 'hg heads --template '\''{node|short}\n'\'''`
lines=`printf '%s\n' "$result" | wc -l`

if [ $lines != 1 ]; then
        cat <<END >&2
WRONG NUMBER OF HEADS! ($lines)
command:
  $*
result:
$result
END
        exit 1
fi

printf '%s\n' "$result"
