#!/bin/bash

set -e -o posix

usage() {
    cat >&2 <<EOF
usage: standalone [operations] [options...]

Operations:

* make-flight [cf,lvextendmax,baseline] [BRANCH]

  Create a flight testing the named branch.

* set-paths [cf] [JOB]

  Setup dist path runvars for JOB from existing build results. Useful
  after recreating a flight to avoid the need to rebuild.

* run-job [cfhrRs] [JOB]

  Run the named JOB.

  Required options: -h HOST

* run-test [cfhrR] [JOB] [TEST]

  Run the named TEST as part of JOB.

  Required options: -h HOST

* reset-host [cf] [JOB]

  Allow a job which has been run before to run on a different host or
  hosts next time. Otherwise osstest will complain if you change the
  host(s) which a job is running on on successive runs.

* get-job-status [cf] [JOB]

  Prints the status (pass, fail, running, etc) of the given job to
  stdout.

Options:

-c FILE, --config=FILE        Use FILE as configuration file
-f FLIGHT, --flight=FLIGHT    Operate on FLIGHT
-h HOST, --host=HOST          Test host, HOST can also be ident=HOST can
                              be given multiple times, not that the
                              order matters in some cases (e.g run-test)
-r, --reuse                   Do not wipe test host (default)
-R, --noreuse, --reinstall    Wipe the test host (if job or test does so)
-s, --simulate, --dry-run     Dry run, printing what would be run
--lvextendmax=GB              Limit the size of the build logical volume
--baseline                    Create a baseline flight instead of a tip flight

--help                        This message

EOF
}

if [ $# -lt 1 ] ; then
    echo "Need an operation" >&2
    usage
    exit 1
fi

op=$1 ; shift

if [ x$op = x--help ] ; then
    usage
    exit 0
fi

TEMP=$(getopt -o c:f:h:rRs --long config:,flight:,host:,reuse,noreuse,reinstall,simulate,dry-run,lvextendmax:,baseline,help -- "$@")

eval set -- "$TEMP"

if [ -n "${OSSTEST_CONFIG}" ]; then
    config=${OSSTEST_CONFIG}
elif [ -f local-config ]; then
    config=local-config
else
    config=$HOME/.xen-osstest/config
fi
flight="standalone"
hosts=
reuse=1 # Don't blow away machines by default
dryrun=0
lvextendmax=50 # Leave some LVM space free for running tests
nobaseline=y

add_host() {
    local h=$1
    case $h in
	*=*)
	    local ident=${h/=*}
	    h=${h/*=}
	    hosts="$hosts $ident=$h"
	    ;;
	*)
	    hosts="$hosts host=$h"
	    ;;
    esac
}

export_hosts_environ() {
    for h in $hosts ; do
	local ident=${h/=*}
	h=${h/*=}
	eval export OSSTEST_HOST_${ident^^}=$h
    done
}

while true ; do
    case "$1" in
	-c|--config) config=$2; shift 2;;
	-f|--flight) flight=$2; shift 2;;
	-h|--host)   add_host $2; shift 2;;
	-r|--reuse)  reuse=1;   shift 1;;
	-R|--noreuse|--reinstall)reuse=0;shift 1;;
	-s|--simulate|--dry-run)dryrun=1;shift 1;;
	--lvextendmax)lvextendmax=$2; shift 2;;
	--baseline)nobaseline=n; shift 1;;
	--help)      usage; exit 0;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;

    esac
done

. ./cri-getconfig

WebspaceLog=`OSSTEST_CONFIG=$config getconfig WebspaceLog`
if [ ! -r "$WebspaceLog" ] ; then
    echo "WARNING: Cannot read apache logs at $WebspaceLog. Some tests may fail" >&2
fi

if ! ssh-add -l >/dev/null ] ; then
    echo "WARNING: Unable to access ssh-agent. Some tests may fail" >&2
fi

if [ $reuse -eq 0 ]; then
    echo "WARNING: Will blow away machine(s)..."
    echo "Press ENTER to confirm."
    read
fi

db="standalone.db"
if [ ! -f $db ] ; then
    echo "No $db? Run standalone-reset." >&2
    exit 1
fi

if [ -z "$config" ] ; then
    echo "No config specified." >&2
    exit 1
fi
IFS_saved=$IFS
IFS=:
for c in $config ; do
    if [ -z "$c" -o ! -r "$c" ] ; then
        echo "Cannot read config $c." >&2
        exit 1
    fi
done
IFS=$IFS_saved

need_flight() {
    if [ -z "$flight" ] ; then
	echo "run-job: Need a flight" >&2
	exit 1
    fi
}
need_host() {
    if [ "x$hosts" = x ] ; then
	echo "run-job: Need a host" >&2
	exit 1
    fi
}

check_repos() {
    # We don't care about the answer, just the error checking and
    # logging to stderr.
    OSSTEST_CONFIG=$config getrepos >/dev/null
}

ensure_logs() {
    if [ ! -d "logs" ] ; then
	mkdir "logs"
    fi
    if [ ! -d "logs/$flight" ] ; then
	mkdir "logs/$flight"
    fi
}

with_logging() {
    local log=$1; shift
    ensure_logs
    savelog -c 300 "$log" >/dev/null
    "$@" 2>&1 | tee "$log"
    rc=${PIPESTATUS[0]}
    if [ $rc -ne 0 ] ; then
	echo "FAILED rc=${rc}" >&2
	exit $rc
    fi
}

job_status() {
    flight=$1; shift
    job=$1; shift

    OSSTEST_CONFIG=$config \
        ./cs-adjust-flight $flight job-status $job
}

# other potential ops:
# - run standalone reset

case $op in
    help)
        usage
	exit 0
	;;

    make-flight)
        check_repos
        need_flight

        if [ $# -lt 1 ] ; then
            echo "make-flight: Need branch" >&2
            exit 1
        fi

        branch=$1; shift

        DAILY_BRANCH_POSTMAKE_HOOK=exit\ 0 \
        OSSTEST_USE_HEAD=y \
        BRANCHES_ALWAYS="$branch" \
        BUILD_LVEXTEND_MAX="$lvextendmax" \
        OSSTEST_FLIGHT=$flight \
        OSSTEST_CONFIG=$config \
        OSSTEST_NO_BASELINE=$nobaseline \
            with_logging logs/$flight/make-flight.log ./cr-daily-branch "$@" $branch
        ;;

    set-paths)
	need_flight

	if [ $# -lt 1 ] ; then
	    echo "set-paths: Need job" >&2
	    exit 1
	fi

	job=$1; shift

	for d in '' xen kern libvirt ; do
	    runvar="path_${d}dist"
 	    path="build/${d}dist.tar.gz"
	    if [ -f "logs/$flight/$job/$path" ] ; then
		./cs-adjust-flight -v $flight runvar-set $job $runvar $path
	    fi
	done

	if [ -f "logs/$flight/$job/build/kerndist.tar.gz" ] ; then
	    KERNEL_VER=$(tar tzf logs/$flight/$job/build/kerndist.tar.gz |\
		sed -n -e 's,^lib/modules/\(.*\)/modules.dep$,\1,p')
	    if [ -n "$KERNEL_VER" ]; then
		./cs-adjust-flight -v $flight \
		    runvar-set $job kernel_ver $KERNEL_VER
	    fi
	fi
	;;

    reset-host)
	need_flight;

	if [ $# -lt 1 ] ; then
	    echo "run-job: Need job" >&2
	    exit 1
	fi

	job=$1; shift
	./cs-adjust-flight -v $flight runvar-del $job '/(?:\w+_)?host$'
	;;

    run-job)
	need_flight; need_host

	if [ $# -lt 1 ] ; then
	    echo "run-job: Need job" >&2
	    exit 1
	fi

	job=$1; shift

	export_hosts_environ

        OSSTEST_CONFIG=$config \
	OSSTEST_FLIGHT=$flight \
	OSSTEST_HOST_REUSE=$reuse \
	OSSTEST_SIMULATE=$dryrun \
	    with_logging logs/$flight/$job.log ./sg-run-job $job

	status=`job_status $flight $job`
	echo "$flight.$job status = $status" >&2
	if [ "x$status" != xpass ] ; then exit 1; fi

	;;
    run-test)
	need_flight; need_host

	if [ $# -lt 2 ] ; then
	    echo "run-test: Need job + test" >&2
	    exit 1
	fi

	job=$1; shift
	ts=$1; shift

	OSSTEST_CONFIG=$config \
	OSSTEST_FLIGHT=$flight \
	OSSTEST_HOST_REUSE=$reuse \
	OSSTEST_JOB=$job \
	    with_logging logs/$flight/$job.$ts.log ./$ts $hosts "$@"
	;;

    get-job-status)
	need_flight;

	if [ $# -ne 1 ] ; then
	    echo "get-job-status: Need job" >&2
	    exit 1
	fi

	job=$1; shift

	job_status $flight $job

	;;
    *)
	echo "Unknown op $op" ; exit 1 ;;
esac
