#!/bin/bash
#
# Prints the results of each cr-daily-branch's make-flight
#
# Usage:
#    ./standalone-generate-dump-flight-runvars [BRANCH....]
#
# If no BRANCHes specified, does all that are normally run by
# cr-daily-branch or out of crontab.

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2014 Citrix Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e -o posix

set -o pipefail

mkdir -p tmp

procs=""

if [ $# = 0 ]; then
   set `./mg-list-all-branches`
fi

if [ "x$AP_FETCH_MEMO_KEEP" = x ]; then
	rm -rf tmp/apmemo
	mkdir tmp/apmemo
fi
export AP_FETCH_PFX='./memoise tmp/apmemo'

# In the future it might be nice for this script to arrange to use a
# separate standalone.db, in tmp/ probably, for each different branch.
# That would avoid a lot of needless write contention over the single
# db, and make it possible to use `eatmydata' if it is installed.

perbranch () {
    log=tmp/make-flight.$branch.log
    flight=check_${branch//[-._]/_}
}

# Good grief, handling background proceesses from shell is a pain.
#
# For stupid historical reasons, background processes start with
# SIGINT (and QUIT) ignored (SuSv3 2.11).  bash does not currently
# offer a way to ask it not to do this; nor is there a reliable way to
# put the SIGINT handling back to normal.
#
# "trap - INT" can be used to put the handling back in recent versions
# of bash (eg Debian jessie), but earlier versions are buggy, so
# we use perl.
#
# However, there is still a race: if the signal arrives just after the
# fork, after the shell has (in the child) set it to to IGN, but
# before Perl has put it back, the child might still escape.
# There is no reasonable way to deal with this race.  So the result
# may still be slightly racy in the case that s-g-d-f-r is ^C'd right
# after starting.
#
# Hopefully in the future we can fix this with something like
# "shopt -s no_async_sig_ignore".  See
# https://lists.gnu.org/archive/html/bug-bash/2015-10/msg00077.html

for branch in $@; do
    perbranch
    perl -e '
        $SIG{$_}=DFL foreach qw(INT QUIT HUP);
	kill 1, $$ unless getppid=='$$';
	exec @ARGV or die $!;
    ' \
    ./standalone make-flight -f $flight $branch >$log 2>&1 &
    procs+=" $branch=$!"
done

perproc () {
    branch=${proc%=*}
    pid=${proc##*=}
    perbranch
}

for proc in $procs; do
    perproc
    if ! wait $pid; then
       set +e
       cat $log >&2
       echo >&2 "make-flight $branch failed"
       exit 1
    fi
done

for proc in $procs; do
    perproc
    ./mg-show-flight-runvars -a $flight | sed "s/^/`printf '%-26s ' $branch`/"
done
