#!/usr/bin/perl -w
# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

our %timeout= qw(Migrate      400);

tsreadconfig();

our $sho = selecthost($ARGV[0]);
our $dho = selecthost($ARGV[1]);
our $gho = selectguest($ARGV[2],$sho);

sub migrate () {
    guest_checkrunning($sho,$gho) or die $gho->{Name};
    my $err= target_check_ip($gho);  die "$err $gho->{Name}" if defined $err;
    toolstack($sho)->migrate($gho, $dho, $timeout{Migrate});
}

guest_await_dhcp_tcp($gho, 5);
guest_check_up($gho);
migrate();
guest_check_up($gho);
