#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

tsreadconfig();

our ($ho,$gho) = ts_get_host_guest(@ARGV);

sub destroy () {
    guest_destroy($ho, $gho);
    guest_checkrunning($ho, $gho) and die $gho->{Name};
}

guest_await_dhcp_tcp($gho, 5);
destroy();
target_ping_check_down($gho);
