#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

tsreadconfig();

our ($ho,$gho) = ts_get_host_guest(@ARGV);

sub start () {
    guest_umount_lv($ho, $gho);
    my $cmd= toolstack()->{Command}." create ".
        $r{ $gho->{Guest}.'_'. toolstack()->{CfgPathVar} };
    target_cmd_root($ho, $cmd, 30);
}

sub checkstart () {
    guest_checkrunning($ho, $gho) or die "$gho->{Name} not running";
}

start();
checkstart();
guest_await($gho, target_var($gho,'boot_timeout'));
guest_check_up($gho);
