#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

our %timeout= qw(Migrate      400);

tsreadconfig();

our $sho = selecthost($ARGV[0]);
our $dho = selecthost($ARGV[1]);
our $gho = selectguest($ARGV[2],$sho);

sub migrate () {
    guest_checkrunning($sho,$gho) or die $gho->{Name};
    my $err= guest_check_ip($gho);  die "$err $gho->{Name}" if defined $err;
    target_cmd_root($sho,
		    toolstack()->{Command}
		    ." migrate $gho->{Name} $dho->{Name}",
		    $timeout{Migrate});
}

guest_await_dhcp_tcp($gho, 5);
guest_check_up($gho);
migrate();
guest_check_up($gho);
