#!/usr/bin/perl -w
# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use Osstest;
use Osstest::TestSupport;

tsreadconfig();

foreach my $ident (@ARGV) {
    my $host;
    if ($ident =~ s/\=(.*)$//) {
        $host = $1;
    }
    $host ||= $r{$ident};;
    $host ||= $ENV{'OSSTEST_HOST_'.uc $ident};
    $host ||= $c{"TestHost_$ident"};
    $host ||= $c{TestHost};
    $host || die "need host setting for $ident";

    my $expected = $ENV{'OSSTEST_HOST_'.uc $ident}
                   || $c{"TestHost_$ident"}
                   || $c{TestHost};

    die "$ident configuration mismatch $r{$ident} != $expected"
	if $r{$ident} && $r{$ident} ne $expected;

    store_runvar($ident, $host);
}
