#!/usr/bin/perl -w
# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

tsreadconfig();

our ($whhost) = @ARGV;
our $ho= selecthost($whhost);

sub fail () {
    my $log= "/var/log/xen/osstest-hostfail";
    my $interface= get_host_property($ho,'interface force','eth0');
    target_cmd_root($ho, <<END);
set -e
savelog $log
( exec </dev/null >$log
  exec 2>&1
  sleep 5
  ifconfig $interface down
  ifconfig p$interface down
  init 0 ) &
END
}   

fail();
target_await_down($ho, 20);
