#!/usr/bin/perl -w

use strict qw(vars);
use Osstest;
use DBI;
use IO::File;
use POSIX;
use Osstest::TestSupport;

tsreadconfig();

our ($whhost) = @ARGV;
$whhost ||= 'host';
our $ho= selecthost($whhost);

sub try_fetch_logs ($$) {
    my ($lho, $logfilepats) = @_;
    my $ok= 0;
    foreach my $logfilepat (@$logfilepats) {
        my $logfileslist= $logfilepat;
        if ($logfileslist =~ m/[*?]/) {
            if (!eval {
                $logfileslist=
                    target_cmd_output_root($lho, <<END);
                        chmod a+r $logfilepat >/dev/null 2>&1 ||:
                        echo $logfilepat
END
                1;
            }) {
                logm("logfile $logfilepat pattern expansion failed: $@");
                next;
            }
            next if $logfileslist eq $logfilepat;
        }
        foreach my $logfile (split / /, $logfileslist) {
            my $llogfile= $logfile;
            $llogfile =~ s,/,-,g;
            $llogfile= "$lho->{Name}--$llogfile";
            logm("fetching $logfile to $llogfile");
            if (!eval {
                target_getfile_root($lho,60, $logfile,"$stash/$llogfile");
		if ($logfile !~ m/\.gz$/) {
		    stat("$stash/$llogfile") or die "$stash/$llogfile $!";
		    if ((stat _)[7] > 100000) {
			my $r= system 'gzip','-9vf','--',"$stash/$llogfile";
			die "$r $!" if $r;
		    }
		}
                1;
            }) {
                logm("logfile $logfile fetch failed: $@");
                next;
            }
        }
        $ok= 1;
    }
    return $ok;
}

sub try_cmd_output_save ($;$) {
    my ($cmd, $dfn) = @_;
    if (!defined $dfn) {
        $dfn= $cmd;
        $dfn =~ s,-,-,g;
        $dfn =~ s/ /_/g;
        $dfn =~ s/[^-+._,=0-9a-zA-Z]/#/g;
        $dfn= $ho->{Name}."-output-$dfn";
    }
    my $output;
    if (!eval {
        $output= target_cmd_output_root($ho, $cmd);
        1;
    }) {
        logm("failed to run $cmd: $@");
        return;
    }
    my $fh= open_unique_stashfile(\$dfn);
    print $fh $output or die $!;
    close $fh or die $!;
}

sub fetch_logs_host_guests () {
    my $logs= [qw(
                  /var/log/kern.log*
                  /var/log/syslog*
                  /var/log/daemon.log*

                  /var/log/dmesg*
                  /var/log/user.log*

                  /var/log/installer/syslog*
                  /var/log/installer/partman*

                  /var/log/xen/xend.log*
                  /var/log/xen/xend-debug.log*
                  /var/log/xen/xen-hotplug.log*
                  /var/log/xen/domain-builder-ng.log*
                  /var/log/xen/qemu-dm*
                  /var/log/xen/xl*.log
                  /var/log/xen/osstest*
                  /var/log/xen/xenstored*

                  /var/log/xenstored*

                  /var/log/xen/console/*

                  /var/log/xen-tools/*

                  /boot/config*

                  /etc/xen/*

                  )];
    if (!try_fetch_logs($ho, $logs)) {
        logm("log fetching failed, trying hard host reboot...");
        if (!eval {
            target_reboot_hard($ho);
            1;
        }) {
            logm("host reboot failed, abandoning log fetches: $@");
            return;
        }
    }

    foreach my $cmd
        (
         'xl info',
         'cat /proc/cpuinfo',
         'xl list',
         'xm list',
         'xm list --long',
         'xenstore-ls -fp',
         'ifconfig',
         'route -vn',
         'brctl show',
         'lvm lvs',
    'ps wwwaxf -eo pid,tty,stat,time,nice,psr,pcpu,pmem,nwchan,wchan:25,args',
         ) {
            try_cmd_output_save($cmd);
        }

    my $sth= $dbh_tests->prepare(<<END);
        SELECT name FROM runvars WHERE flight=? AND job=?
            AND name LIKE '%_domname'
            ORDER BY name
END
    $sth->execute($flight, $job);
    my $row;
    while ($row= $sth->fetchrow_hashref) {
        my $gn= $row->{name};
        $gn =~ s/_domname$//;
        fetch_logs_guest($gn);
    }
    $sth->finish();
}

sub fetch_logs_guest ($) {
    my ($gn) = @_;
    logm("saving logs for $gn");
    my $gho= selectguest($gn,$ho);
    if (!eval {
        guest_find_domid($ho,$gho);
        1;
    }) {
        logm("cannot find domid: $@");
        return;
    }
    my $consolecmd= toolstack()->{Command}." console $gho->{Name}";
    try_cmd_output_save("sleep 1 | $consolecmd | cat",
                        "guest-$gho->{Name}-console");

    if (defined $gho->{Vcpus}) {
        foreach (my $vcpu=0; $vcpu < $gho->{Vcpus}; $vcpu++) {
            try_cmd_output_save("/usr/lib/xen/bin/xenctx $gho->{Domid} $vcpu");
        }
    }

    if (!eval {
        my $vnc= guest_vncsnapshot_begin($ho,$gho);
        guest_vncsnapshot_stash($ho,$gho,$vnc, "$gho->{Name}--vnc.jpeg");
        1;
    }) {
        logm("cannot get vnc snapshot: $@");
    }
}

$ho->{SerialMethobj}->fetch_logs();
fetch_logs_host_guests();
logm("logs captured to $stash");
