#!/usr/bin/perl -w
# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

our %timeout= qw(Migrate      400);

tsreadconfig();

our $sho = selecthost($ARGV[0]);
our $dho = selecthost($ARGV[1]);
our $gho = selectguest($ARGV[2],$sho);

our $log;

sub startremus () {
    guest_checkrunning($sho,$gho) or die $gho->{Name};
    $log= "/var/log/xen/osstest-remus-$gho->{Name}.log";
    target_cmd_root($sho, <<END);
set -e
savelog $log
( set -e
  exec </dev/null >$log
  remus --no-net $gho->{Name} $dho->{Name} 2>&1 ) &
END
}

sub awaitready () {
    poll_loop($timeout{Migrate}, 10, 'remus startup', sub {
	my $loghead= target_cmd_output_root($sho, "head -40 $log", 100);
	my @matches= $loghead =~ m/^All memory is saved/mg;
	return undef if @matches >= 2;
	$loghead =~ /.*$/ or die;
	return "log: $&";
    });
}

guest_check_up($gho);
startremus();
awaitready();
target_cmd_root($gho, "echo remus $gho->{Name}: ok", 20);
guest_check_remus_ok($gho,$sho,$dho);
guest_check_up($gho);
