#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use Osstest::TestSupport;

tsreadconfig();

my $gn= pop(@ARGV);
our @ho= map { selecthost($_) } @ARGV;
our $gho= selectguest($gn,$ho[0]);

guest_check_remus_ok($gho, @ho);
guest_check_up($gho);
