#! /bin/sh

set -e

# grub-mkconfig helper script.
# Copyright (C) 2006,2007,2008,2009,2010  Free Software Foundation, Inc.
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

prefix="/usr"
exec_prefix="${prefix}"
datarootdir="${prefix}/share"

. "${datarootdir}/grub/grub-mkconfig_lib"

CLASS="--class gnu-linux --class gnu --class os --class xen"

chain_xen_entry () {
    vendor="$1"
    if [ ! -f /boot/efi/EFI/$vendor/xen.efi ] ; then
	return
    fi
    title=$(gettext_quoted "Chainload $vendor Xen")
    xmessage="$(gettext_printf "Chainloading $vendor Xen ...")"
    printf "menuentry '${title}' ${CLASS} {\n"
    prepare_grub_to_access_device \
	`${grub_probe} --target=device /boot/efi/EFI/$vendor/xen.efi` \
	| grub_add_tab
    cat <<EOF
	echo	'$xmessage'
	chainloader	/EFI/$vendor/xen.efi
}
EOF
}

for i in ${GRUB_ENABLE_XEN_UEFI_CHAINLOAD} ; do
    chain_xen_entry $i
done
