#! /bin/sh
### BEGIN INIT INFO
# Provides:          osstest-confirm-booted
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Confirm fully booted
# Description:
### END INIT INFO

# This is part of "osstest", an automated testing framework for Xen.
# Copyright (C) 2009-2013 Citrix Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


NAME=stop-bootlogd

case "$1" in
  stop|restart)
        rm -f /dev/shm/osstest-confirm-booted
        ;;
  start|reload|force-reload)
        ;;
  *)
        echo "Usage: $NAME {start|stop|restart|reload|force-reload}" >&2
        exit 3
esac

case "$1" in
  start|reload|force-reload)
        if mount | egrep '^[^ 	][^ 	]* on /dev/shm type tmpfs ' >/dev/null
        then
                touch /dev/shm/osstest-confirm-booted
        else
                echo >&2 '/dev/shm is not a tmpfs ?'; exit 1
        fi
        ;;
esac
